"""
Reusable cleanup script for system/test-created data.

USAGE:
  cd /app/backend && python scripts/cleanup_test_data.py            # dry-run
  cd /app/backend && python scripts/cleanup_test_data.py --apply    # actually delete

Strategy (option 1a from product): SURGICAL pattern-based delete.
We only touch rows that look test-created:
  • emails matching @test.com / @example.com / @example.org
  • names starting with "Test", "Smoke", "QA", "Detail Tester", "Scanner Tester",
    "Refund Tester", "Badge", "Curl", "Auto", "Iteration", "fake"
  • test-flagged orders (order_number starting "EVT-" generated by tests)
  • verification tokens older than 7 days

Collections scoped:
  orders, refunds, event_showtimes, event_locations, bookings, receipts,
  bills, ticket_validations, revoked_access_tokens, refresh_tokens,
  verification_tokens, commission_configs (only QA name pattern).

Production seed accounts (4) are NEVER touched:
  admin@test.com, superadmin@oryno.com, operator@test.com, customer@test.com
"""
import os
import re
import sys
import argparse
import asyncio
from datetime import datetime, timezone, timedelta

from motor.motor_asyncio import AsyncIOMotorClient

try:
    from dotenv import load_dotenv  # type: ignore

    load_dotenv(os.path.join(os.path.dirname(__file__), "..", ".env"))
except ImportError:
    pass


PROTECTED_EMAILS = {
    "admin@test.com",
    "superadmin@oryno.com",
    "operator@test.com",
    "customer@test.com",
}

# Email patterns considered test data (always lowered before matching).
TEST_EMAIL_RE = re.compile(
    r"@(example\.com|example\.org|test\.test|qa\..*|sample\.com)$",
    re.IGNORECASE,
)

# Name patterns — case-insensitive substring match
TEST_NAME_PATTERNS = [
    r"^smoke\b", r"^qa\b", r"^test\b", r"^detail tester$",
    r"^scanner tester$", r"^refund tester$", r"^badge tester$",
    r"^curl\b", r"^auto\b", r"^iteration\b", r"^fake\b",
]
TEST_NAME_RE = re.compile("|".join(TEST_NAME_PATTERNS), re.IGNORECASE)

# Showtime / Location title patterns
TEST_TITLE_RE = re.compile(
    r"^(smoke|qa|detail|scanner|badge|curl|poster|no poster|refund)\b|"
    r"\s+(show|venue)\s+[0-9a-f]{4,8}$",
    re.IGNORECASE,
)


def _is_test_email(email: str | None) -> bool:
    if not email:
        return False
    e = email.lower().strip()
    if e in PROTECTED_EMAILS:
        return False
    return bool(TEST_EMAIL_RE.search(e))


def _is_test_name(name: str | None) -> bool:
    if not name:
        return False
    return bool(TEST_NAME_RE.search(name.strip()))


def _is_test_title(title: str | None) -> bool:
    if not title:
        return False
    return bool(TEST_TITLE_RE.search(title.strip()))


async def _connect():
    url = os.environ["MONGO_URL"]
    db_name = (os.environ.get("DB_NAME") or os.environ.get("MONGO_DB_NAME") or "oryno_webapp").strip()
    client = AsyncIOMotorClient(url)
    return client, client[db_name]


async def _scan_and_collect_test_ids(db):
    """First pass — return the set of test user_ids, test order_ids, test
    showtime_ids and test location_ids so the second pass can cascade-delete."""
    test_user_ids: set[str] = set()
    async for u in db.users.find({}, {"_id": 1, "email": 1, "full_name": 1, "first_name": 1}):
        if u.get("email", "").lower() in PROTECTED_EMAILS:
            continue
        if _is_test_email(u.get("email")) or _is_test_name(u.get("full_name") or u.get("first_name")):
            test_user_ids.add(u["_id"])

    test_showtime_ids: set[str] = set()
    async for s in db.event_showtimes.find({}, {"_id": 1, "title": 1}):
        if _is_test_title(s.get("title")):
            test_showtime_ids.add(s["_id"])

    test_location_ids: set[str] = set()
    async for loc in db.event_locations.find({}, {"_id": 1, "name": 1}):
        if _is_test_title(loc.get("name")):
            test_location_ids.add(loc["_id"])

    # Orders are test if booked by a test user OR for a test showtime OR if the
    # contact_name matches a test pattern.
    test_order_ids: set[str] = set()
    async for o in db.orders.find({}, {"_id": 1, "user_id": 1, "booking_details": 1, "order_number": 1, "service_id": 1}):
        contact_name = (o.get("booking_details") or {}).get("contact_name", "")
        if (
            o.get("user_id") in test_user_ids
            or _is_test_name(contact_name)
            or o.get("service_id") in test_showtime_ids
            or (o.get("order_number") or "").startswith("EVT-")
        ):
            test_order_ids.add(o["_id"])

    return {
        "users": test_user_ids,
        "orders": test_order_ids,
        "showtimes": test_showtime_ids,
        "locations": test_location_ids,
    }


async def _delete(coll, query: dict, dry: bool) -> int:
    if dry:
        return await coll.count_documents(query)
    res = await coll.delete_many(query)
    return res.deleted_count


async def main(apply: bool):
    client, db = await _connect()
    dry = not apply

    targets = await _scan_and_collect_test_ids(db)
    print(f"[scan] test users={len(targets['users'])} orders={len(targets['orders'])} "
          f"showtimes={len(targets['showtimes'])} locations={len(targets['locations'])}")

    rolling_stats: dict[str, int] = {}

    # 1. Refunds whose order is a test order
    if targets["orders"]:
        n = await _delete(db.refunds, {"order_id": {"$in": list(targets["orders"])}}, dry)
        rolling_stats["refunds"] = n
    # 2. Ticket validations on test orders
    if targets["orders"]:
        n = await _delete(db.ticket_validations, {"order_id": {"$in": list(targets["orders"])}}, dry)
        rolling_stats["ticket_validations"] = n
    # 3. Receipts on test orders
    if targets["orders"]:
        n = await _delete(db.receipts, {"order_id": {"$in": list(targets["orders"])}}, dry)
        rolling_stats["receipts"] = n
    # 4. Bills tied to test users
    if targets["users"]:
        n = await _delete(db.bills, {"user_id": {"$in": list(targets["users"])}}, dry)
        rolling_stats["bills"] = n
    # 5. The orders themselves
    if targets["orders"]:
        n = await _delete(db.orders, {"_id": {"$in": list(targets["orders"])}}, dry)
        rolling_stats["orders"] = n
    # 6. Bookings (legacy collection) for test users
    if targets["users"]:
        n = await _delete(db.bookings, {"user_id": {"$in": list(targets["users"])}}, dry)
        rolling_stats["bookings"] = n
    # 7. Event showtimes matching test titles
    if targets["showtimes"]:
        n = await _delete(db.event_showtimes, {"_id": {"$in": list(targets["showtimes"])}}, dry)
        rolling_stats["event_showtimes"] = n
    # 8. Event locations matching test titles
    if targets["locations"]:
        n = await _delete(db.event_locations, {"_id": {"$in": list(targets["locations"])}}, dry)
        rolling_stats["event_locations"] = n
    # 9. Commission configs created by tests (QA pattern)
    n = await _delete(db.commission_configs, {"name": {"$regex": r"^(QA|Smoke|Test)\b", "$options": "i"}}, dry)
    rolling_stats["commission_configs"] = n
    # 10. Verification tokens >7 days old (auto-expiring noise)
    cutoff = datetime.now(timezone.utc) - timedelta(days=7)
    n = await _delete(db.verification_tokens, {"created_at": {"$lt": cutoff}}, dry)
    rolling_stats["verification_tokens_aged"] = n
    # 11. Revoked access tokens older than 24h (also expire-by-time)
    cutoff = datetime.now(timezone.utc) - timedelta(hours=24)
    n = await _delete(db.revoked_access_tokens, {"revoked_at": {"$lt": cutoff}}, dry)
    rolling_stats["revoked_tokens_aged"] = n
    # 12. Refresh tokens older than 30 days
    cutoff = datetime.now(timezone.utc) - timedelta(days=30)
    n = await _delete(db.refresh_tokens, {"created_at": {"$lt": cutoff}}, dry)
    rolling_stats["refresh_tokens_aged"] = n
    # 13. Test users themselves (LAST so the cascading queries above resolved)
    if targets["users"]:
        n = await _delete(db.users, {"_id": {"$in": list(targets["users"])}}, dry)
        rolling_stats["users"] = n

    header = "DRY-RUN (no rows changed)" if dry else "APPLIED"
    print(f"\n=== {header} ===")
    for k, v in rolling_stats.items():
        print(f"  {k:30s} → {v}")
    if dry:
        print("\nRe-run with --apply to actually delete.")
    client.close()


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="Actually run the deletions")
    args = ap.parse_args()
    asyncio.run(main(args.apply))
